### ISSUE TITLE
ArchLinux PKGBUILD

### ISSUE THREAD

**Issue by jgmdev** [Expensify/Bedrock#108]
Just wanted to say that I discovered this project today and found it really interesting (given my love for sqlite) so I wanted to give it a test run and created an ArchLinux package:

https://aur.archlinux.org/packages/bedrock/

Thanks for contributing such an interesting project, looking forward to make use of it on the future!

**Comment by quinthar** [comment]
Awesome, thank you!  Out of curiosity, what commands would someone run to
install this into Arch?  (Sorry, I'm not familiar with the platform -- I'm
looking for the Arch equivalent of what's on bedrockdb.com for Ubuntu.)
 Additionally, what is the process for updating that binary when we do new
releases?  Thanks!

**Comment by jgmdev** [comment]
To install on arch there are various methods for this user submitted package but most popular would be:
```sh
yaourt -S bedrock
```
This would fetch a fresh a copy of github bedrock repo and compile, then generate a package that can be easily installed. To update to latest codebase a user just needs to do the same and the version of the package will be automatically calculated from the git repo.

**Comment by quinthar** [comment]
Oh wow, that's bad ass.  So it just pulls down the HEAD of the master
branch and runs with that?  Why am I not using Arch...

**Comment by jgmdev** [comment]
actually, later on I can move this package to fetch the stable releases tagged here on github and create another package named bedrock-git that does fetch from master branch but for now this should do the trick :)

**Comment by quinthar** [comment]
Oh, actually re-reading that -- to clarify, does the user just need to run`yaourt -S bedrock` and that will download, compile, and install Bedrock?  Or does that just create a package that needs to be installed with some other command?

**Comment by jgmdev** [comment]
It will do the whole process transparently: download, compile, package, install.

**Comment by quinthar** [comment]
Awesome.  I've updated the homepage with these instructions.  Thanks!!

**Comment by quinthar** [comment]
Here's the commit itself -- please review and lmk if there are any mistakes: https://github.com/Expensify/Bedrock/commit/ff34f74dde2f91cd323be40785174b6c05e95380
