### ISSUE TITLE
Improve child job handling

### ISSUE THREAD

**Issue by quinthar** [Expensify/Bedrock#109]
Background:
====
Bedrock::Jobs has the concept of a "child" job: just set `parentJobID` when calling `CreateJob` and the parent/child linkage will be retained.  The design pattern is that the parent would create child jobs to work in parallel, and then "pause" itself (by calling `FinishJob` on itself) to to wait for the children to complete.  When all children complete, the parent would be "resumed", and harvest the results of the children.

Problem:
====
There are a couple concerns with the current design:

1. The [code that "resumes" the parent](https://github.com/Expensify/Bedrock/blob/master/plugins/Jobs.cpp#L548-L553) doesn't explicitly verify that it's currently `PAUSED`.  In theory it should always be, but if it's not for any reason, this might double-resume the parent, with undefined results.

2. Right now the child is created in the `QUEUED` state, meaning it can start running the instant it's created.  This means it could even finish prior to the parent calling `FinishJob` on itself, meaning Bedrock will think all the children are done and never pause itself.  If the worker only looks at the children upon resume (which is what the design assumes), then it might never harvest the results.

3. The design assumes that children are created by their own parents, OR by a sibling.  Race conditions abound if arbitrary parent relationships are allowed, but it's safe for a job to create its own children (in which the parent will be `RUNNING`), as well as for one child to create a job with the same parent as its own (in which case the parent will be `PAUSED`).

4. There is no explicit way for a worker to know if the job they're processing is running for the first time, or if it's paused and being resumed.  Rather, the parent job is expected to save an array of child jobs into its own data while calling `FinishJob` (and thus pausing itself), and then querying the results of those jobs via Bedrock::DB.  This works, but is clunky.

5. Though we don't currently have any jobs that work this way, if a parent job creates more child jobs after being resumed (eg, has child jobs, is paused/resumed, and then creates more children), when it's resumed a second time it's unclear which of the child jobs were part of the first or second batch.

Solution:
====
I suggest we tighten this up as follows:

1. Verify that the parent is `PAUSED` when *any* child (not just the last) calls `FinishJob`, and return `405 Parent must be PAUSED when children are running`.  By making this check early and often, we help shorten the window between whatever problem happened and we discover it.

2. Create children in the `PAUSED` state, and then mark them as `QUEUED` when the parent is paused.  However, if the parent is `PAUSED` (indicating a child is creating a sibling job) then set the new child to `QUEUED`.

3. Verify that the parent is `RUNNING`  or `PAUSED` when any attempt is made to create a child job, and return `405 Only parents can create their own children` otherwise.

4. When finishing a child job, mark it as `FINISHED` rather than deleting it immediately.  Also, when resuming a parent job, return a JSON object (eg, associative array) of the data objects for all `FINISHED` child jobs, with the `jobID` as the key, and an object consisting of `data` and `state`. This clearly signals to the worker "You are being resumed after finishing a bunch of child jobs", as well as alleviates the need for the worker to manually query the results of the children.  This is backwards compatible with the current method, but obviates it over time.

5. When finishing a parent job, delete any `FINISHED` child jobs *even if* there are other `PAUSED` child jobs outstanding (as is done by step (2) above).  This way the next time the parent is resumed, the child jobs returned (via step (4) above) will only be for the latest round.
    * Admittedly, this might be a bit of a premature optimization given that we don't actually intend to do this right now.  But given the low cost of the change and the generality of this tool, I suggest we tighten up this edge case now while we're thinking of it.

Thoughts or concerns on the above before I get started?  @cead22 @tylerkaraszewski @iwiznia  @mcnamamj

**Comment by iwiznia** [comment]
> There is no explicit way for a worker to know if the job they're processing is running for the first time, or if it's paused and being resumed. Rather, the parent job is expected to save an array of child jobs into its own data while calling FinishJob (and thus pausing itself), and then querying the results of those jobs via Bedrock::DB. This works, but is clunky.

There is no explicit way to know, but we decided that it was the responsibility of the parent job to track that (which we do on the Harvester jobs with the `isWaiting` param. 

While I agree with the changes proposed here, I'm hesitant to implement them now, given that we already have a performance problem with the jobs system and this will only make things worse. I think we should stop and fix our current performance problems before adding more logic, more queries and more load the the jobs system.

**Comment by quinthar** [comment]
>> There is no explicit way for a worker to know if the job they're processing is running for the first time, or if it's paused and being resumed. Rather, the parent job is expected to save an array of child jobs into its own data while calling FinishJob (and thus pausing itself), and then querying the results of those jobs via Bedrock::DB. This works, but is clunky.
>
> There is no explicit way to know, but we decided that it was the responsibility of the parent job to track that (which we do on the Harvester jobs with the isWaiting param).

Yep, I agree this isn't strictly needed.  However, I think this is a cleaner solution than `isWaiting`.  Mainly I think `isWaiting` was fine for our first parent/child job, but now that we're adding more it's time to clean it up a bit so we don't extend a non-ideal paradigm.

> While I agree with the changes proposed here, I'm hesitant to implement them now, given that we already have a performance problem with the jobs system and this will only make things worse. I think we should stop and fix our current performance problems before adding more logic, more queries and more load the the jobs system.

I don't see how any of this aggravates the load problem.  This is about tightening up edge cases and making parent/child jobs work better.

**Comment by iwiznia** [comment]
> I don't see how any of this aggravates the load problem

This is adding more queries to the existing commands, If we add more queries then times for each command will be higher than now, thus aggravating the current performance problem.

**Comment by quinthar** [comment]
Well yes, in an absolute sense this is true.  But the queries these are adding are all trivial, and thus will be instant.  Adding these won't slow anything down (eg, if they existed, removing these wouldn't speed anything up).  The problem we have is `GetJob` takes too long, but this is unrelated to that.  Let's not use `GetJob`'s performance problems as a reason to block all other development on Bedrock.

**Comment by iwiznia** [comment]
The current queries are also supposed to be trivial and instant, but reality says they are not, and we don't yet have a clear understanding on why. Also, even if they are "instant" they will add some overhead, even if it's just a little bit.
To be clear, I'm not saying we should block development, we can develop the changes as long as we don't deploy them. Or if we want to deploy them, we must be ready to revert them if they indeed make things worse.

**Comment by quinthar** [comment]
@iwiznia says "if we make the tests to make sure we are not going to make the current performance situation worse, then I'm fine with adding them now" -- so I'm going to take this as a green light.

**Comment by cead22** [comment]
> When finishing a parent job, delete any FINISHED child jobs even if there are other PAUSED

@quinthar how is this scenario possible? I thought the parent job wouldn't resume until ALL child jobs finished

Also, are you interested in implementing this yourself?

**Comment by quinthar** [comment]
>> When finishing a parent job, delete any FINISHED child jobs even if there are other PAUSED
>
> @quinthar how is this scenario possible? I thought the parent job wouldn't resume until ALL child jobs finished

This could happen if the parent creates more children (in the `PAUSED` state) after being resumed to process a previous set of children (in the `FINISHED` state).

**Comment by quinthar** [comment]
I've updated the design with this text:

> The design assumes that children are created by their own parents, OR by a sibling. Race conditions abound if arbitrary parent relationships are allowed, but it's safe for a job to create its own children (in which the parent will be RUNNING), as well as for one child to create a job with the same parent as its own (in which case the parent will be PAUSED).

So, we still prevent creating children of `QUEUED` jobs (which I think its the important, dangerous case, because jobs that are `QUEUED` should be assumed to be able to run at any moment, so no external operation upon them is safe).
