### ISSUE TITLE
Add Bedrock::Jobs::CancelJob

### ISSUE THREAD

**Issue by quinthar** [Expensify/Bedrock#110]
Problem:
====
There are scenarios where a parent has a series of children, but the work done by one of the children obviates the others.  In this scenario it'd be nice to make a "best attempt" to cancel the other children (eg, if they haven't yet started `RUNNING`), but currently there is no safe way to do this.

Solution:
=====
Add a formal `CancelJob` command that:

1. Applies the `CancelJob` logic recursively to all children of the job being cancelled
2. If this job is `RUNNING`, do nothing -- the train has already left the station.
3. If the job is `FINISHED` or `CANCELLED`, do nothing -- there's nothing left to cancel.
4. If the job is `QUEUED`:
    * If the job has a `parentJobID` (indicating it is a child), then the child job is put into the `CANCELLED` state.  If this is the last child, the parent is resumed.
    * Otherwise, delete the job
5. If the job is `PAUSED`, do nothing -- one of its children must still be running so we can't cancel the parent.

How does this sound?  @cead22 @iwiznia @tylerkaraszewski @mcnamamj

**Comment by iwiznia** [comment]
> If the job is PAUSED, do nothing -- one of its children must still be running so we can't cancel the parent.

In this case, shouldn't we iterate over all children and try to cancel them, before trying to cancel the parent?

**Comment by quinthar** [comment]
That is handled by (1) and will already be done by the time we get to (5).
