### ISSUE TITLE
Official Bedrock Docker image

### ISSUE THREAD

**Issue by g41797** [Expensify/Bedrock#1782]
Hi
Now I am working on set of _queue adapters_ for different brokers/services:

- [Nats](https://github.com/g41797/queue-nats)
- [AWS SQS](https://github.com/g41797/queue-sqs)
- [Apache Pulsar](https://github.com/g41797/queue-pulsar)

For every broker above I have official Docker image.

I can not find official Docker image for Bedrock, only [unofficial one](https://hub.docker.com/r/abdelmalekkkkk/bedrock)

Are you going to supply it?

Thanks

**Comment by fukawi2** [comment]
Hi @g41797, thanks for your interest in Bedrock. Docker is not a technology we use, so there are no plans to release an official docker image at this time.

**Comment by adworacz** [comment]
Is this being reconsidered, now that this repository has been [updated with a Dockerfile?](https://github.com/Expensify/Bedrock/commit/c28ff57db82824d41608a3b216fb47017224ef62)

**Comment by fukawi2** [comment]
We merged the Dockerfile to make it easier for those who do, but we still don't use docker internally ourselves, and have no plans to do so, sorry.

**Comment by adworacz** [comment]
I think that's a completely fair response. I appreciate providing the Dockerfile as you've done already, publishing to a public registry is a nice to have that other members of the community can pick up.

I might even put together a publishing workflow in a few months, depending on my availability.

**Comment by fukawi2** [comment]
Thanks for understanding - it's probably something that we _could_ do, but since we don't use docker (and don't have a huge amount of docker knowledge), it would likely be a disservice to provide "half-hearted" images.
