### ISSUE TITLE
Docs need navigation bar

### ISSUE THREAD

**Issue by styfle** [Expensify/Bedrock#314]
Typically there is some sort of hierarchy or navigation bar on a docs website.

For example [Bootstrap](https://getbootstrap.com/docs/4.0/getting-started/theming/) has a navbar on the left hand side to see the different sections of the docs.

I think that Bedrock should have something similar. For example, I finally found [vs_mysql](http://bedrockdb.com/vs_mysql.html) but it doesn't have any navigation to know where I am or where to go next.

**Comment by quinthar** [comment]
Yep very fair point.  The website was whipped up pretty quick to see if there was enough interest to invest into making a better one -- this is a tool we very actively use internally and we want to open it up to the world, but at the same time we don't really stand to gain much by the outside world using it so we haven't prioritized making the site look great.  Thanks for enduring its current state, and the more people use it, the more we'll put into the site!

**Comment by styfle** [comment]
> The website was whipped up pretty quick to see if there was enough interest to invest into making a better one

Hi David,

I am interested in the concept! 😄 

But without proper documentation or a roadmap, I don't think Bedrock is something I can convince my manager to adopt.

**Comment by quinthar** [comment]
Ah, understood.  In the meantime please post any questions here, or perhaps in our Gitter chat room, and happy to help! https://gitter.im/Expensify-Bedrock/Lobby
