### ISSUE TITLE
Explore hosted log storage alternatives to self-hosting ElasticSearch

### ISSUE THREAD

**Issue by quinthar** [Expensify/Bedrock#338]
Problem:
====
We pay $32K/mo (which might go to as low as $20K if we reserve instances) for ElasticSearch -- on top of a bunch of engineering time to maintain it.  Scaling that to 10x will be expensive and difficult, so let's just double check that we're on the right path.

Solution:
====
Price out a few cloud hosted log services, such as Splunk (on the high end) and ?? (on the low end).
 
Cc: @Expensify/infra

**Comment by coleaeason** [comment]
Going to close this, this is in the wrong repo.
