### ISSUE TITLE
Cant install on Ubuntu Server 16.04

### ISSUE THREAD

**Issue by macmattias** [Expensify/Bedrock#34]
Like what I read about bedrock and I was just about to start a small project - perfect to try something new.
Tried to install the three first steps worked just fine but the last, install sent me this:
`sudo apt-get install bedrock
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bedrock : Depends: libpcrecpp0 but it is not installable
E: Unable to correct problems, you have held broken packages.
`
What should I do about that?

**Comment by macmattias** [comment]
I tried to install libpcrecpp0 but got that it is named libpcrecpp0v5, installed that no change, tried to make a symlink with the name libpcrecpp0 no luck.

**Comment by coleaeason** [comment]
Hey there! Sorry about that, the instructions on the index page are for trusty. There is a Xenial repo with a package that has the correct require, you just need to change the sources.list file to pull from the right one. You can either edit `/etc/apt/sources.list.d/bedrock.list` and replace `trusty` with `xenial` OR you can just copy and paste this line which will download and install the correct file for you:
```
sudo wget -O /etc/apt/sources.list.d/bedrock.list https://apt.bedrockdb.com/ubuntu/dists/xenial/bedrock.list
```

After updating the file you'll need to `sudo apt-get update` and `sudo apt-get install bedrock` again.
