### ISSUE TITLE
Documentation on how the synchronization happens?

### ISSUE THREAD

**Issue by tonyarkles** [Expensify/Bedrock#35]
I just came across this today via O'Reilly's Four Short Links, and I can't seem to find anything about how the actual replication and consensus stuff work on the project.

**Comment by quinthar** [comment]
Hey there, I've written up some details on synchronization here: http://bedrockdb.com/synchronization.html  Please reopen if you have more questions.  Thanks!

**Comment by tonyarkles** [comment]
@quinthar you rock. Thank you ver much!
