### ISSUE TITLE
any plan to becomr package manager for debian

### ISSUE THREAD

**Issue by xcombelle** [Expensify/Bedrock#350]
This product looks fantastic. I would love it become a standard part of Debian whivh is my distrinution of choice Any plan to make it easier for installing om it and their derivatives?

**Comment by quinthar** [comment]
We keep talking about doing this, but just haven't gotten around to it.  We
run our own private apt repo for internal use, but we keep meaning to push
our latest builds up to the public apt repo -- it just hasn't gotten to the
top of the priority queue.  Thankfully, however, it's pretty easy to build
and I hope you'll give that a shot in the meantime.  Thanks!
