### ISSUE TITLE
Unclear on how the duplication works, and what happens if a single DB is updated directly.

### ISSUE THREAD

**Issue by arjunsharma** [Expensify/Bedrock#37]
This is partially related to #35. I would love to get a more in depth explanation of how Bedrock actually does its duplication, and what happens in certain common cases that distributed databases run into. But in particular, I had a use case while playing around with Bedrock that I would love more documentation about.

I followed the multizone example where I had 3 different Bedrock nodes running. I created a database with an auto-incrementing primary key. I created a record (ID=1) and saw it replicated to all 3 databases. I then shut them all down, and opened node0.db directly with SQLite and added a new record (ID=2). I then restarted all of the nodes, and node0 showed both records (ID=1 and ID=2), but node1 and node2 only showed the second record (ID=2). I then shut down all of the nodes, and deleted the unreplicated record (ID=2) from node0. I then restarted all of the nodes, and created a new record (ID=3). Except that node1 and node2 showed its ID as 2, but node0 showed its ID as 3.

A deeper dive into how Bedrock works would explain this behavior and allow me to know what kinds of things I should/shouldn't do. For example, it appears that I shouldn't expect that I could migrate a single database directly, and then start nodes and expect them to replicate; instead I would have to make all database changes while multiple nodes were already running.

**Comment by quinthar** [comment]
Hey there, I've written up some thoughts here: http://bedrockdb.com/synchronization.html  Please reopen if you have more questions.  Thanks for asking!
