### ISSUE TITLE
Add error message for non-existing options

### ISSUE THREAD

**Issue by ShahriyarR** [Expensify/Bedrock#39]
The test:

```
sh@sh-ubuntu:~$ bedrock --wth
sh@sh-ubuntu:~$ 

sh@sh-ubuntu:~$ bedrock --version
sh@sh-ubuntu:~$ 
```

The way it should act -> "Error: unknown option --wth, please use -help to list available options"

**Comment by quinthar** [comment]
Good idea!  Would you like to submit a PR to do this?

**Comment by quinthar** [comment]
This isn't a bad idea, but it's not one I'm personally passionate about doing (or hiring someone to do). Going to close this unless someone else wants to take it on.
