### ISSUE TITLE
bedrock : Depends: libstdc++6 (> 7.1) but 5.4.0-6ubuntu1~16.04.9 is to be installed

### ISSUE THREAD

**Issue by gsacre** [Expensify/Bedrock#403]
Hi,

I'm trying to install bedrock on an Ubuntu 16.04 image on Google Computing Engine.
Here is the error I'm getting:

```
Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 bedrock : Depends: libstdc++6 (> 7.1) but 5.4.0-6ubuntu1~16.04.9 is to be installed
E: Unable to correct problems, you have held broken packages.
```

It's a bare image, nothing has been installed on it except docker.

I have successfully installed bedrock (and ran it) on a VM for another client where I installed Ubuntu 16.04 from the official ISO in January.

Am I missing something?

**Comment by swhi3635** [comment]
Hi there,
Bedrock relies on a version of GLIBCXX that is not included the latest (as of 2018-03-20) version of `libstdc++6` included in the default apt repositories for Ubuntu 14.04 and 16.04.  You will need to add a repository that includes `libstdc++6 > 7.1`.  Here is the one that we use: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

Instructions to fix:
1. `sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
2. `sudo apt-get update`
3. `sudo apt-get install libstdc++6`

You should be able to successfully install and run bedrock once the new `libstdc++6` package has been installed.

Hope this helps.

**Comment by gsacre** [comment]
I confirm that the fix works!
