### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [Expensify/Bedrock#42]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [the macro "SDELETE"](https://github.com/Expensify/Bedrock/blob/0732e39259651a3dc7baff528d8f97662bb6ee5c/libstuff/libstuff.h#L396 "Update candidate: SDELETE()").

**Comment by quinthar** [comment]
Oh, very interesting!

**Comment by flodnv** [comment]
Thanks for the report, fixed by https://github.com/Expensify/Bedrock/pull/47
