### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Expensify/Bedrock#43]
I would like to point out that an identifier like "[`_CT_`](https://github.com/Expensify/Bedrock/blob/0732e39259651a3dc7baff528d8f97662bb6ee5c/libstuff/libstuff.h#L51 "Update candidate")" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by quinthar** [comment]
What would you recommend?

**Comment by elfring** [comment]
Will the affected identifiers work also without [extra underscores](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by quinthar** [comment]
Very interesting!  I think we'll leave these for now but let's definitely fix these in the future if they cause conflicts with other libraries or any other problems.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by quinthar** [comment]
Sounds good, please go ahead and submit a pr!
