### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [Expensify/Bedrock#44]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/Expensify/Bedrock/blob/551cbbea5449fd014e44cdd106d33a714ee9a2ed/main.cpp#L72)" does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by quinthar** [comment]
Sounds great to me.  Would you like to submit a PR that does this?

**Comment by quinthar** [comment]
This isn't a bad idea, but it's not one I'm personally passionate about doing (or hiring someone to do).  Going to close this unless someone else wants to take it on.
