### ISSUE TITLE
Bedrock Logo?

### ISSUE THREAD

**Issue by apavlo** [Expensify/Bedrock#468]
I added an entry for Bedrock to my encyclopedia of databases:

https://dbdb.io/db/bedrock

Is there a logo that I can use for the article?

Thanks!

-- Andy

**Comment by wmertens** [comment]
It seems that the logo is simply the word "Bedrock" in a 400-weight Helvetica Neue…

**Comment by quinthar** [comment]
Yes sorry about that -- there isn't really any fancy logo, just the word.  Thanks for asking!

**Comment by apavlo** [comment]
Noted. Added logo from website: https://dbdb.io/db/bedrock

Thanks!
