### ISSUE TITLE
Encrypted Communication Between Nodes

### ISSUE THREAD

**Issue by vlasky** [Expensify/Bedrock#475]
Hello,

Unless I am mistaken, It doesn't seem that communication between nodes is encrypted with TLS/SSL.

Are there any plans to introduce it? This really is mandatory for an enterprise app operating over a WAN.

**Comment by jungle-boogie** [comment]
Perhaps running a VPN between your two nodes would be better than TLS code being added to this project.

Check out https://www.wireguard.com/quickstart

**Comment by quinthar** [comment]
@jungle-boogie is correct -- we view it as a best practice to run over a VPN, rather than TLS encrypted over the internet.
