### ISSUE TITLE
Won't compile on MacOSX

### ISSUE THREAD

**Issue by quinthar** [Expensify/Bedrock#509]
Problem:
====
Ideally you could use the instructions outlined here: https://github.com/Expensify/Bedrock/blob/dbarrett_osxCompile/docs/index.md

```
# Clone out this repo:
git clone https://github.com/Expensify/Bedrock.git

# Install some dependencies with Brew (see: https://brew.sh/)
brew update
brew install gcc@6
brew install pcre

# Build it
cd Bedrock
make

# Create an empty database (See: https://github.com/Expensify/Bedrock/issues/489)
touch bedrock.db

# Run it (press Ctrl^C to quit, or use -fork to make it run in the backgroud)
./bedrock

# Connect to it in a different terminal using netcat
nc localhost 8888

# Type "Status" and then enter twice to verify it's working
# See here to use the default DB plugin: http://bedrockdb.com/db.html
```

However it breaks in at least two ways:

* `make` doesn't clone the subrepo for some reason
* `make` fails with PCRE:
    ```
    Undefined symbols for architecture x86_64:
      "pcrecpp::RE::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pcrecpp::RE_Options const*)", referenced from:
          pcrecpp::RE::RE(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libstuff.a(libstuff.o)
          pcrecpp::RE::RE(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libbedrock.a(Jobs.o)
          pcrecpp::RE::RE(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pcrecpp::RE_Options const&) in libbedrock.a(MySQL.o)
    ld: symbol(s) not found for architecture x86_64
    ```

Solution:
====
To fix:
1. Check out a fresh copy of `dbarrett_osxCompile`
2. Follow the instructions
3. If something breaks, fix, goto 1
4. If the instructions need to be updated, do so in the branch
5. Submit a PR

**Comment by quinthar** [comment]
FYI, anyone who wants to take this issue, there's some money in it for you! https://www.upwork.com/jobs/~01e7ad7e026a20a5e1

**Comment by flodnv** [comment]
@quinthar to fix the PCRE thing, in the past `brew install pcre` fixed it. Is that still the case or not?

**Comment by treps** [comment]
no that did not fix it. It is installed, and all of the headers and such
compile fine, but for some reason it fails in the linking stage.

**Comment by topilski** [comment]
I can resolve this issue, my suggestion is move your build system into CMake after that your life will be more easy.

**Comment by treps** [comment]
Hm, I'd prefer to stick with classic make, as it works everywhere else and
I don't think is the constraint in this particular issue.  I'd prefer not
to change the while build system just to solve this one issue.

**Comment by topilski** [comment]
It will be solve a lot of issues in future.
