### ISSUE TITLE
Tag v1.0 release

### ISSUE THREAD

**Issue by quinthar** [Expensify/Bedrock#53]
Can you please tag the exact version that corresponds to the v1.0 public release?  I'd like to review the commit since then to discuss when to do a v1.1 and so on.

**Comment by quinthar** [comment]
Or this might go best to @righdforsa -- not sure.

**Comment by tylerkaraszewski** [comment]
Is that the commit that was on github at the time you gave your presentation on it?

**Comment by quinthar** [comment]
I'm thinking whatever version was used to make the apt-get repo version.

On Mon, Nov 14, 2016 at 6:46 PM, Tyler Karaszewski <notifications@github.com

**Comment by coleaeason** [comment]
```
1.0.20~7a4c774
```
Is the version that was in the repo when your presentation ended. `7a4c774` being the short commit hash.

**Comment by tylerkaraszewski** [comment]
I think this is correct:
https://github.com/Expensify/Bedrock/releases/tag/1.0

**Comment by quinthar** [comment]
Awesome, thanks!

-david
