### ISSUE TITLE
Question: Where to report an issue for the Bedrock website's behavior?

### ISSUE THREAD

**Issue by stefanos82** [Expensify/Bedrock#657]
Hello everyone.

I wanted to ask: is this the expected behavior you originally had in mind for the documentation?

Below you can see the index page with a standard title message "Bedrock by Expensify".

![image](https://user-images.githubusercontent.com/1777466/60376328-dda44880-9a16-11e9-8a5b-084b5e2694f4.png)

and in this picture the title remains the same; actually every single page displays the same title tag: "Bedrock by Expensify".

![image](https://user-images.githubusercontent.com/1777466/60376390-5d321780-9a17-11e9-8255-991adbd7470b.png)

Is it possible to have the `h1` tag at the most left of the `title` tag? It would make it easier to be found via search engines.

**Comment by BJWes** [comment]
Hi there, I'm sure there is some way to do it, thanks for the suggestion.
Can you submit a PR to fix it?

**Comment by stefanos82** [comment]
Inside `docs` I can see the markdown files, but I have never done something like this, as title is part of the default layout.

Let me see what I can do.
