### ISSUE TITLE
Bedrock doesn't respond to queries

### ISSUE THREAD

**Issue by dinedal** [Expensify/Bedrock#789]
I hope someone can help me: I just created https://github.com/Expensify/Bedrock/pull/788

The tests pass and it is running, but it doesn't seem to respond no matter what I send on 8888. Any advice?

```
$ nc localhost 8888
SELECT 1;
Query: SELECT 1;
Query:
SELECT 1;
```
All with no response.

Additionally, the mysql client always responds with `ERROR 1045 (28000): Access denied`

**Comment by coleaeason** [comment]
Hi @dinedal, I'm pretty sure the issue you're having with your queries over netcat is that you are not adding new lines at the end of your query. Bedrock speaks psuedo http, meaning it waits for empty new lines to know that it has received all of the data off of a socket. You should try something like this:

```
$ nc localhost 8888
Query: SELECT 1;

```

Note the extra blank new line.

WRT to the mysql client, this seems like a separate issue and should be catalogued as such.
