### ISSUE TITLE
Question: minimum requirements

### ISSUE THREAD

**Issue by mhamann** [Expensify/Bedrock#816]
Any idea of the minimum system requirements for running a bedrock instance? Wondering how different the requirements are from SQLite. For instance, could I deploy a cluster with fairly minimal CPU/RAM (e.g. like 0.1 CPU and a few MB of RAM) and then scale it up later if load increases? Or is there a "minimum" like 1GB RAM and a full CPU?

Thanks!

**Comment by coleaeason** [comment]
I'm not sure we've ever tested running bedrock on very minimal hardware such as partial CPUs and a few MB of RAM. Bedrock is specifically designed to scale with core count, and that is the way we run it in production. Additionally, there are features that will take advantage of more RAM as well, i.e. you can enable mmap'ing of the entire database assuming you have enough RAM available. There is no reason (that I can think of) that you could not run it on a minimal set of hardware as you describe, but the performance may be far from ideal.
