### ISSUE TITLE
"Error querying the database: Unknown authentication plugin `@BhfHt/-4^Z,'."

### ISSUE THREAD

**Issue by janpio** [Expensify/Bedrock#818]
When trying to drop in Bedrock into an application that usually uses a MySQL database (using `mysql://root:root@127.0.0.1:3306/bedrock` after creating doing `touch bedrock.db` and `bedrock -fork`), I get the following error message:

`Error querying the database: Unknown authentication plugin @BhfHt/-4^Z,'.`

Does this make sense to anyone and point in a specific direction I should look at?

**Comment by janpio** [comment]
Still exists in current releases and I have no idea how to debug :/

**Comment by tylerkaraszewski** [comment]
What version of the MySQL client are you using for this? It's entirely possible our plugin is out-of-date, and it also has limited (read: none) of the authentication support in MySQL, as bedrock doesn't use it (though it should fake it and connect anyway).

**Comment by janpio** [comment]
We are using a Rust driver for MySQL (currently mysql-async) here. https://github.com/prisma/quaint/blob/6fafb89c9e814c55ee351eb92e9e7ea19203a17b/Cargo.toml#L86 to be exact, so https://github.com/blackbeam/mysql_async/tree/v0.23.0.

**Comment by coleaeason** [comment]
I merged in a change that makes Bedrock work with the Rust driver you're using. You can find the details in the attached PR.

I'm not sure when we will do a new release to the apt-repo of the current HEAD, but if you want to keep developing immediately you can check out the master branch in your tests and build the binary yourself in the mean time.

**Comment by janpio** [comment]
Thanks, I will try to look for new releases so I can just use an existing release.

**Comment by coleaeason** [comment]
I actually went ahead and sent out a new release this morning too, so this code should be in the newest released version available in the apt repo, `2020.08.13~d2d17eb-16.04`

**Comment by janpio** [comment]
It is, thanks. I can also reproduce the problem you were seeing and will now try to debug what is going on there.
