### ISSUE TITLE
Make generate_series() available

### ISSUE THREAD

**Issue by jveres** [Expensify/Bedrock#944]
Hi! Would it be possible to compile sqlite with series.c thus making `generate_series()` available?
https://sqlite.org/series.html

**Comment by quinthar** [comment]
Good question!  Can you submit a PR to make it happen?

**Comment by jveres** [comment]
Okay, I figured it out and got it working. Before I issue the PR could you please specify which sqlite release/trunk are you using for [building](https://sqlite.org/amalgamation.html) `sqlite3.c` for _libstuff_? I guess it's [d2de81a24f](https://www.sqlite.org/cgi/src/info/d2de81a24f82d71d), correct?

**Comment by quinthar** [comment]
@tylerkaraszewski can you answer this?

**Comment by jveres** [comment]
So `sqlite_source_id()` gives `2020-08-31 20:37:00 1d98472277ff131960a7718cd57af5b6ed4ead811a9220a6eb35ff505bf5alt2` which means that [this](https://www2.sqlite.org/src/info/1d98472277ff1319) check-in has been used but since modified in Bedrock.
I have no confidence in simply overwriting `libstuff/sqlite3.c` with a new version even though tests pass.

**Comment by jveres** [comment]
I ended up adding `generate_series()` and a bunch of other extensions to my custom Docker build.
https://github.com/jveres/bedrock-xsim
